model:
  backbone: yolo_v8_xs_backbone_coco
  classes: [jempol, five, three, v sign]
  fpn_depth: 2
  bounding_box_format: xywh

train:
  strategy: freeze
  epochs: 100
  accelerator: tpu
  classification_loss: binary_crossentropy
  box_loss: ciou
  optimizer_1:
    class_name: Adam  
    config:
      learning_rate: 0.0001
      global_clipnorm: 10.0
    
  optimizer_2:
    class_name: Adam
    config:
      learning_rate: 0.000001
      global_clipnorm: 10.0


logger:  wandb

dataset:
  path: ../datasets
  type: XML
  val_split: 0.2
  batch_size: 16
  image_size: (640, 640)
  previous_bounding_box_format: xywh
  Augmenter:




